{{- with .Values }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .artifact.appName }}
  namespace: default
  annotations:
    sealedsecrets.bitnami.com/strict: "true"
spec:
  encryptedData:
  {{ if eq .artifact.profile "production" }}
  {{- range $key, $value := .artifact.enc.production }}
    {{ $key }}: {{ $value }}
  {{- end }}
  {{ else if eq .artifact.profile "staging" }}
  {{- range $key, $value := .artifact.enc.staging }}
    {{ $key }}: {{ $value }}
  {{- end }}
  {{ else }}
  {{- range $key, $value := .artifact.enc.development }}
    {{ $key }}: {{ $value }}
  {{- end }}
  {{ end }}
  template:
    metadata:
      name: {{ .artifact.appName }}
      namespace: default
{{- end }}
