apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.artifact.appName }}
spec:
  ports:
  # Port that accepts gRPC and JSON/HTTP2 requests over HTTP.
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http2
  selector:
    app:  {{ .Values.artifact.appDomain }}
